### ISSUE TITLE
Which versions are current?

### ISSUE THREAD

**Issue by thunderkid** [geogebra/giac#2]
First, thanks for the excellent giac system. It deserves to be far more widely known, and I'm glad to see it now on github, which I expect will greatly help its visibility.

I'm trying to understand the relationship between the various giac versions, and which ones are currently maintained. This isn't clear to me from the documentation. Here are a few specific items:

1. When I build minigiac from the source in this repository, it seems to behave slightly differently from the command-line giac that is installed using `apt-get install xcas`. Does minigiac have the full functionality of the command-line xcas-giac? . For example, in minigiac entering `sqrt(3)` returns `√3`, whereas in xcas-giac it returns `sqrt(3)`. This substitution is occurring on line 374 of `symbolic.cc` and seems independent of any conditionals. Does this mean for example that the full xcas-giac does not use `symbolic.cc`?
2. Does this repo even contain the source for the full xcas-giac, or is that being replaced by minigiac? (I see that in a commit you mention that `icas` was renamed to `minigiac`, and in an xcas installation there's a link `giac->icas`, which suggest to me that perhaps xcas-giac is not currently being maintained?).
3. Is the node version of giac maintained? The front readme says it's not, but I'm not clear whether that refers to just the pure-javascript port, or also the node-gyp version. [This readme](https://github.com/geogebra/giac/tree/master/src/nodegiac), on the other hand, doesn't mention that it's not maintained, but when I follow its instructions to install giac from npm, the build fails with the current versions of ubuntu, node, gcc. And that page claims to provide a link to `nodegiac.js`, but that link is broken.
4. Is the WASM version currently maintained? When I try to run `./gradlew downloadEmsdk installEmsdk activateEmsdk createGiacWasmJs` with latest versions I get errors in `emccGiacJsWasm`.

My own use case is that I need to call giac functions from node/javascript, in a low-latency performant way (maybe 100 calls/second). I really want to use an active maintained branch of the code, but currently I'm just using [this](https://www-fourier.univ-grenoble-alpes.fr/~parisse/giacjs.tar.gz) pure-javascript port (which is also presumably slower than c++ or WASM though perhaps with less potential for unwanted latency), and I'm trying to work out the best way to do this based on which versions are currently maintained.

**Comment by zbynek** [comment]
Hi! This repository contains all parts Giac needed to run it as a library for GeoGebra. Thie .gradle files definining the build are only used by GeoGebra, not by `xcas-giac`. That means some of the preprocessor flags are different when you use the Gradle build system.

The Node version is no longer actively maintained. The last NPM version that was actively used is `1.23.69259` , it's possible that some releases after that do not work. Also for releases that do work, there are [some tricks](https://github.com/kovzol/giac-electron-example/blob/master/install.js#L20) needed to use it with NodeJS properly. The goal of NodeJS version was to get it working in GeoGebra's Electron apps, but we eventually switched to WASM because it gives the same results in Electron and in normal browser and is easier to maintain.

WASM is  built after each commit (using [this Jenkinsfile](https://github.com/geogebra/giac/blob/master/Jenkinsfile#L36))  and is sucessfully used. Maybe if you share the errors you're getting we can hep you ientify the problem.

**Comment by thunderkid** [comment]
Thanks, that's very useful. So it sounds as though the best approach to using giac in node is to use your WASM version. 

To compile WASM I'm following the instructions in the comments in `build.gradle`. The error I'm getting from `./gradlew downloadEmsdk installEmsdk activateEmsdk createGiacWasmJs` is the following. (It's the `createGiacWasmJs` part that's failing):

```

> Task :emccGiacJsWasm FAILED
Linking: /giac/emsdk/emscripten/latest/emcc build/objs/giac-wasm.js/modpoly.o build/objs/giac-wasm.js/misc.o build/objs/giac-wasm.js/quater.o build/objs/giac-wasm.js/tinymt32.o build/objs/giac-wasm.js/first.o build/objs/giac-wasm.js/intg.o build/objs/giac-wasm.js/mathml.o build/objs/giac-wasm.js/intgab.o build/objs/giac-wasm.js/plot3d.o build/objs/giac-wasm.js/input_lexer.o build/objs/giac-wasm.js/sym2poly.o build/objs/giac-wasm.js/derive.o build/objs/giac-wasm.js/isom.o build/objs/giac-wasm.js/gen.o build/objs/giac-wasm.js/permu.o build/objs/giac-wasm.js/alg_ext.o build/objs/giac-wasm.js/opengl.o build/objs/giac-wasm.js/unary.o build/objs/giac-wasm.js/pari.o build/objs/giac-wasm.js/solve.o build/objs/giac-wasm.js/vecteur.o build/objs/giac-wasm.js/maple.o build/objs/giac-wasm.js/input_parser.o build/objs/giac-wasm.js/rpn.o build/objs/giac-wasm.js/desolve.o build/objs/giac-wasm.js/csturm.o build/objs/giac-wasm.js/gausspol.o build/objs/giac-wasm.js/plot.o build/objs/giac-wasm.js/risch.o build/objs/giac-wasm.js/gauss.o build/objs/giac-wasm.js/subst.o build/objs/giac-wasm.js/threaded.o build/objs/giac-wasm.js/lin.o build/objs/giac-wasm.js/usual.o build/objs/giac-wasm.js/moyal.o build/objs/giac-wasm.js/kdisplay.o build/objs/giac-wasm.js/sparse.o build/objs/giac-wasm.js/kadd.o build/objs/giac-wasm.js/symbolic.o build/objs/giac-wasm.js/ti89.o build/objs/giac-wasm.js/index.o build/objs/giac-wasm.js/cocoa.o build/objs/giac-wasm.js/identificateur.o build/objs/giac-wasm.js/ezgcd.o build/objs/giac-wasm.js/help.o build/objs/giac-wasm.js/global.o build/objs/giac-wasm.js/series.o build/objs/giac-wasm.js/modfactor.o build/objs/giac-wasm.js/tex.o build/objs/giac-wasm.js/prog.o build/objs/giac-wasm.js/ifactor.o src/giac.js/prebuilt/libmpfr.a src/giac.js/prebuilt/libgmp.a --js-library src/giac.js/js/time.js -DGIAC_GGB -o build/binaries/giacggb.wasm/giacggb.js -Oz -v -s EXPORTED_FUNCTIONS=['_caseval'] -s EXTRA_EXPORTED_RUNTIME_METHODS=["cwrap"] --memory-init-file 0 -s TOTAL_MEMORY=67108864
 "/giac/emsdk/upstream/bin/wasm-ld" -o build/binaries/giacggb.wasm/giacggb.wasm build/objs/giac-wasm.js/modpoly.o build/objs/giac-wasm.js/misc.o build/objs/giac-wasm.js/quater.o build/objs/giac-wasm.js/tinymt32.o build/objs/giac-wasm.js/first.o build/objs/giac-wasm.js/intg.o build/objs/giac-wasm.js/mathml.o build/objs/giac-wasm.js/intgab.o build/objs/giac-wasm.js/plot3d.o build/objs/giac-wasm.js/input_lexer.o build/objs/giac-wasm.js/sym2poly.o build/objs/giac-wasm.js/derive.o build/objs/giac-wasm.js/isom.o build/objs/giac-wasm.js/gen.o build/objs/giac-wasm.js/permu.o build/objs/giac-wasm.js/alg_ext.o build/objs/giac-wasm.js/opengl.o build/objs/giac-wasm.js/unary.o build/objs/giac-wasm.js/pari.o build/objs/giac-wasm.js/solve.o build/objs/giac-wasm.js/vecteur.o build/objs/giac-wasm.js/maple.o build/objs/giac-wasm.js/input_parser.o build/objs/giac-wasm.js/rpn.o build/objs/giac-wasm.js/desolve.o build/objs/giac-wasm.js/csturm.o build/objs/giac-wasm.js/gausspol.o build/objs/giac-wasm.js/plot.o build/objs/giac-wasm.js/risch.o build/objs/giac-wasm.js/gauss.o build/objs/giac-wasm.js/subst.o build/objs/giac-wasm.js/threaded.o build/objs/giac-wasm.js/lin.o build/objs/giac-wasm.js/usual.o build/objs/giac-wasm.js/moyal.o build/objs/giac-wasm.js/kdisplay.o build/objs/giac-wasm.js/sparse.o build/objs/giac-wasm.js/kadd.o build/objs/giac-wasm.js/symbolic.o build/objs/giac-wasm.js/ti89.o build/objs/giac-wasm.js/index.o build/objs/giac-wasm.js/cocoa.o build/objs/giac-wasm.js/identificateur.o build/objs/giac-wasm.js/ezgcd.o build/objs/giac-wasm.js/help.o build/objs/giac-wasm.js/global.o build/objs/giac-wasm.js/series.o build/objs/giac-wasm.js/modfactor.o build/objs/giac-wasm.js/tex.o build/objs/giac-wasm.js/prog.o build/objs/giac-wasm.js/ifactor.o src/giac.js/prebuilt/libmpfr.a src/giac.js/prebuilt/libgmp.a -L/giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libgl.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libal.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libhtml5.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libcompiler_rt.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc++-noexcept.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc++abi-noexcept.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libdlmalloc.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libc_rt_wasm.a /giac/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/libsockets.a -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --lto-legacy-pass-manager --allow-undefined --strip-debug --export caseval --export stackSave --export stackRestore --export stackAlloc --export __wasm_call_ctors --export __errno_location --export malloc --export-table --export __start_em_asm --export __stop_em_asm -z stack-size=5242880 --initial-memory=67108864 --no-entry --max-memory=67108864 --global-base=1024
 "/giac/emsdk/upstream/bin/wasm-emscripten-finalize" --detect-features --minimize-wasm-changes --dyncalls-i64 build/binaries/giacggb.wasm/giacggb.wasm -o build/binaries/giacggb.wasm/giacggb.wasm
Traceback (most recent call last):
  File "/giac/emsdk/emscripten/latest/emcc.py", line 3471, in <module>
    sys.exit(main(sys.argv))
  File "/giac/emsdk/emscripten/latest/emcc.py", line 3464, in main
    ret = run(args)
  File "/giac/emsdk/emscripten/latest/emcc.py", line 2297, in run
    post_link(options, wasm_target, wasm_target, target)
  File "/giac/emsdk/emscripten/latest/emcc.py", line 2339, in post_link
    emscripten.run(in_wasm, wasm_target, final_js, memfile)
  File "/giac/emsdk/upstream/emscripten/emscripten.py", line 838, in run
    emscript(in_wasm, out_wasm, outfile_js, memfile, shared.DEBUG)
  File "/giac/emsdk/upstream/emscripten/emscripten.py", line 281, in emscript
    metadata = finalize_wasm(in_wasm, out_wasm, memfile, DEBUG)
  File "/giac/emsdk/upstream/emscripten/emscripten.py", line 439, in finalize_wasm
    stdout=subprocess.PIPE)
  File "/giac/emsdk/upstream/emscripten/tools/building.py", line 1567, in run_binaryen_command
    ret = check_call(cmd, stdout=stdout).stdout
  File "/giac/emsdk/upstream/emscripten/tools/shared.py", line 103, in check_call
    return run_process(cmd, *args, **kw)
  File "/giac/emsdk/upstream/emscripten/tools/shared.py", line 93, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 850, in communicate
    stdout = self.stdout.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 287: ordinal not in range(128)

FAILURE: Build failed with an exception.

* Where:
Build file '/giac/build.gradle' line: 1013

* What went wrong:
Execution failed for task ':emccGiacJsWasm'.
> Process 'command '/giac/emsdk/emscripten/latest/emcc'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 7s
55 actionable tasks: 55 executed
root@0121f1014f8e:/giac#
```

**Comment by zbynek** [comment]
What operating system and version of Python are you using? What's the output of `locale`?

**Comment by thunderkid** [comment]
So I've got WASM compilation working (I used a docker container based on ubuntu:22.04). 

I'm trying to understand your WASM files. It looks as though `giac.wasm.js` is an inlined version of `giacggb.js`, but I'm trying to see how to use it. When I use nginx to serve up `/giac/build/binaries/giacggb.wasm/ggb.html`, the giac webpage works fine. If I edit `ggb.html` and change `giacggb.js` to `giac.wasm.js`, then the webpage gets stuck on 'downloading', and the giac calculator does not work. 

Is `giac.wasm.js` working, and if so, how should it be used?

**Comment by zbynek** [comment]
@thunderkid in the HTML you can just add `__ggb__giac = Module;` right after declaration of `Module` and it will work OK (at least it does locally). Since we want to run giac on external sites we didn't want to make `Module` the name of the global variable used for communication between Giac and GeoGebra, but this could be made configurable here if it's helpful for other people building Giac with gradle https://github.com/geogebra/giac/blob/e459b1314cc8187b0717c194ef4efdcbb7200c9f/build.gradle#L1050

**Comment by thunderkid** [comment]
@zbynek Thanks! that works. 

I'm now trying to get WASM working in node. I've tried the following (in node 18), based on [these emscripten docs](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-an-api-written-in-c-c-from-nodejs):

```
var factory = require('./giacggb.js');

factory().then((instance) => {
  var thing = instance._caseval("simplify(22x-14x)"); 
  console.log(thing); 
});
```
where I've manually added the flag `
linkerArgs << '-s' << 'MODULARIZE'
`
into your `emccGiacJsWasm` task in `build.gradle`. It gives the error
```Failed to parse URL from /nodetoy/giacggb.wasm```. (Without the `MODULARIZE` flag it gives the error `factory is not a function`.)

Do you have a working example of calling the WASM from node?

**Comment by zbynek** [comment]
Sorry, I don't have any working NodeJS example.

**Comment by thunderkid** [comment]
@zbynek I got WASM giac working in node with `-O3` and `-sMODULARIZE` emscripten flags, plus an ugly javascript hack to force `isFileUri` to return true. (That certainly shouldn't be necessary, but as WASM evolves I assume it will be called differently anyhow.) It also works in an AWS lambda function. If you are interested I can provide a PR.

I thought I might use your inline `giac.wasm.js` approach for lambda functions, but didn't need it. Did you end up using it for anything or is it just a fossil?
