### ISSUE TITLE
Error in simplify() for expression with integers, squares, square roots.

### ISSUE THREAD

**Issue by thunderkid** [geogebra/giac#4]
The `simplify()` function is failing badly with some simple expressions of integers, squares, and square roots. As an example, if you set
``` x: = ( ( 50 * 2 ^ ( 1 / 2 ) + 40 ) ^ 2 + ( 50 * 2 ^ ( 1 / 2 ) - 80 * 6 ^ ( 1 / 2 ) ) ^ 2 ) ^ ( 1 / 2 )```
then `evalf(x)` gives ` 167.164713168`.
But `evalf(simplify(x))` gives `2.70609218118e+13`.
Looking directly at the output of `simplify(x)` shows some ~50-digit integers, which are clearly incorrect.

You can see this with both the WASM compilation from this repo, and the online version at [https://www-fourier.univ-grenoble-alpes.fr/~parisse/giacjs/simple.html](url).

The xcas/giac C++ command line version does not give the same error - but in that version, `simplify(x)` gives an expression involving `rootof` and a long list of ~20-digit integers, which does not seem like a 'simplification' at all.

**Comment by murkle** [comment]
Thanks, please try this

```
diff alg_ext.cc alg_ext.cc~
731c731
<           symbolic_rootof_list()[vexpr]=k*gaa+gbb;
---
 >           symbolic_rootof_list()[vexpr]=gaa+k*gbb;
734c734
<           symbolic_rootof_list()[v]=k*gaa+gbb;
---
 >           symbolic_rootof_list()[v]=gaa+k*gbb;
```

**Comment by thunderkid** [comment]
Thanks, but I'm having trouble testing this, since your change doesn't seem to alter the WASM files at all. I'm compiling with `./gradlew createGiacWasmJs`. The output file `build/binaries/giacggb.wasm/giacggb.wasm` is completely unaffected by your change. Same for `build/binaries/giacggb.wasm/giac.node.wasm.js`. 
However, the file `build/objs/giac-wasm.js/alg_ext.o` is indeed altered, as I'd expect.

Are there some compiler or linker flags that prevent this from propagating through to the WASM files? Did you test it with some build process other than `./gradlew createGiacWasmJs`?

**Comment by thunderkid** [comment]
Actually, your change does fix the problem. My build process just had some caching issues.
Thanks.
