### ISSUE TITLE
Underconstrained csolve can cause hanging

### ISSUE THREAD

**Issue by thunderkid** [geogebra/giac#5]
The following command:

```csolve([a_r ^ 2 - a_y ^ 2 - 25 = 0, - a_r * cos(a_t) + 5 = 0, - a_r * sin(a_t) + a_y = 0, b_r ^ 2 - b_y ^ 2 - 25 = 0, - b_r * sin(b_t) + b_y = 0, a_y - b_y = 0],[a_y, a_r, a_t, b_y, b_r, b_t])```

causes giac to hang. In either the xcas/giac C++ command line version, or this repo's WASM compilation, it first logs some messages about `Conj Error`, `Bad Argument Value` etc., and then hangs.

In the [online version](https://www-fourier.univ-grenoble-alpes.fr/~parisse/giacjs/simple.html) it shows the command as an input line, but generates no output line, not even an error message.

**Comment by murkle** [comment]
Please try latest commit from Bernard

**Comment by murkle** [comment]
ps and try solve() not csolve()

`{{a_{y} = 0, a_{r} = 5, a_{t} = 0, b_{y} = 0, b_{r} = -5, b_{t} = 0}, {a_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5))))), b_{r} = a_{r}, b_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5)))}, {a_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5))))), b_{r} = a_{r}, b_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5)))}, {a_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), b_{r} = (-a_{r}), b_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5)))}, {a_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), b_{r} = (-a_{r}), b_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5)))}, {a_{y} = 0, a_{r} = 5, a_{t} = 0, b_{y} = 0, b_{r} = 5, b_{t} = 0}, {a_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), b_{r} = a_{r}, b_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5)))}, {a_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), b_{r} = a_{r}, b_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5)))}, {a_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = (a_{r} * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5))))), b_{r} = (-a_{r}), b_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5)))}, {a_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))))), a_{r} = a_{r}, a_{t} = (-2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} + 5))), b_{y} = ((-a_{r}) * sin((2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5))))), b_{r} = (-a_{r}), b_{t} = (2 * atan(sqrt(a_{r}^(2) - 25) / (a_{r} - 5)))}}`

**Comment by thunderkid** [comment]
Yes, the latest commit (3c4a3bf22e66528c3fa5bd483d40822bfbf63279) fixes the hanging.
And thanks also for the `solve` vs `csolve` suggestion. It's 20x faster, and gives much more manageable output. I'll be checking where else I can get away with just using `solve`.
