### ISSUE TITLE
Inequalities behaving inconsistently for edge cases

### ISSUE THREAD

**Issue by thunderkid** [geogebra/giac#6]
After starting a fresh Giac session (i.e. with no variables defined), 

`x^2 > 0` returns `true`.

So Giac seems to be assuming that `x` is real. However, `x` might still be zero, so why return `true`?

On the other hand `x > 0` returns `x > 0`. This seems reasonable - Giac doesn't know whether it's true or not.
And `x^2 > 3` returns `x^2 > 3`, which again seems ok.
And `x^2 < 0` returns `false`, which is ok.
But `x^2 <= 0` also returns `false`, which isn't ok as it doesn't account for the possibility of `x` being zero.

**Comment by zbynek** [comment]
We talked about this with Bernard, he said that

> I'm afraid it will not change in the CAS, because CAS is about doing *effective* algebra and that means you do not want to have a combinatoric explosion of specific cases (even if I could rewrite the whole system to handle all these cases).

so I think this won't be fixed.
